name: update composer hashes
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "composer.json"
      - "composer.lock"
      - "**/*.nix"
      - ".forgejo/workflows/update-composer.yml"
  pull_request:
    paths:
      - "composer.json"
      - "composer.lock"
      - "**/*.nix"
      - ".forgejo/workflows/update-composer.yml"
jobs:
  update-vendor:
    if: |
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: [gpg, native-x86_64-linux]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-home@972508aa672ab101fd85eaffab9671c0a641bc7a # v1
        with:
          gpg-privkey: ${{ secrets.GPG_PRIVKEY }}
          gpg-key-id: ${{ vars.GPG_KEY_ID }}
      - name: perform update
        id: update
        run: |
          set -euo pipefail
          branch="${FORGEJO_HEAD_REF:-$FORGEJO_REF_NAME}"
          git fetch origin "$branch"
          git switch "$branch" 2>/dev/null || git switch -c "$branch" --track "origin/$branch"

          echo "Updating vendor hashes"
          nix run nixpkgs#nix-update -- default -F --version=skip

          if git diff --quiet --exit-code; then
            echo "Hashes are still up to date"
            exit 0
          fi

          git add .
          git commit -m "chore(deps): update composer vendor hashes"
          git push --force-with-lease origin "$branch"
